"""Lint and offline-test Eds Custom Addon (Lua 5.1 / WotLK, no client)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOC_NAME = "Eds Custom Addon.toc"
ADDON_NAME = "Eds Custom Addon"
SOUND_EXTS = {".wav", ".mp3"}
DEFAULT_SOUND_DURATION = 0.5

BANNED = [
    (r"\bIsInGroup\s*\(", "IsInGroup is MoP+; use GetNumPartyMembers/GetNumRaidMembers"),
    (r"\bIsInRaid\s*\(", "IsInRaid is MoP+; use GetNumRaidMembers"),
    (r"\bGetNumGroupMembers\s*\(", "GetNumGroupMembers is MoP+"),
    (r"\bGROUP_ROSTER_UPDATE\b", "GROUP_ROSTER_UPDATE is MoP+"),
    (r"\bC_Timer\.", "C_Timer is not in 3.3.5"),
    (r"\bC_FriendList\.", "C_FriendList is not in 3.3.5; use GetNumFriends/GetFriendInfo"),
    (r'SendChatMessage\s*\(\s*"/xp', "Server XP commands use a dot prefix, not /xp"),
]

def lua_file(rel: str) -> Path:
    return ROOT.joinpath(*rel.replace("\\", "/").split("/"))


def posix(path: Path) -> str:
    return path.resolve().as_posix()


failures = 0


def fail(msg: str) -> None:
    global failures
    failures += 1
    print(f"  FAIL  {msg}")


def ok(msg: str) -> None:
    print(f"  PASS  {msg}")


def sound_category(filename: str) -> str:
    stem = Path(filename).stem.lower()
    if stem.startswith("kill-"):
        return "kill"
    if stem.startswith("lowhp-"):
        return "lowhp"
    return "default"


def probe_sound_duration(path: Path) -> float:
    """Return audio length in seconds; fall back to DEFAULT_SOUND_DURATION."""
    try:
        from mutagen import File as MutagenFile

        audio = MutagenFile(str(path))
        length = getattr(getattr(audio, "info", None), "length", None)
        if length is not None and float(length) > 0:
            return round(float(length), 3)
        print(f"  NOTE  duration probe failed for {path.name}; using {DEFAULT_SOUND_DURATION}s")
    except Exception as exc:  # noqa: BLE001 - lint continues with fallback
        print(f"  NOTE  duration probe failed for {path.name}: {exc}; using {DEFAULT_SOUND_DURATION}s")
    return DEFAULT_SOUND_DURATION


def generate_sound_manifest() -> tuple[dict[str, list[str]], dict[str, float]]:
    """Scan Sounds/ and write manifest.lua (WoW cannot list dirs at runtime)."""
    sounds_dir = ROOT / "Sounds"
    pools: dict[str, list[str]] = {"default": [], "lowhp": [], "kill": []}
    durations: dict[str, float] = {}
    if sounds_dir.is_dir():
        for entry in sorted(sounds_dir.iterdir()):
            if entry.is_file() and entry.suffix.lower() in SOUND_EXTS:
                path = (
                    "Interface\\\\AddOns\\\\"
                    + ADDON_NAME
                    + "\\\\Sounds\\\\"
                    + entry.name
                )
                pools[sound_category(entry.name)].append(path)
                durations[path] = probe_sound_duration(entry)

    def pool_lines(name: str, paths: list[str]) -> list[str]:
        block = [f"{name} = {{"]
        for index, path in enumerate(paths, start=1):
            block.append(f'    [{index}] = "{path}",')
        block.append("}")
        return block

    def duration_lines(entries: dict[str, float]) -> list[str]:
        block = ["WindfurySoundDurations = {"]
        for path, seconds in entries.items():
            block.append(f'    ["{path}"] = {seconds},')
        block.append("}")
        return block

    lines = ["-- Auto-generated by scripts/check.py. Do not edit."]
    lines.extend(pool_lines("WindfurySounds", pools["default"]))
    lines.extend(pool_lines("WindfurySoundsLowHp", pools["lowhp"]))
    lines.extend(pool_lines("WindfurySoundsKill", pools["kill"]))
    lines.extend(duration_lines(durations))
    manifest = sounds_dir / "manifest.lua"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return pools, durations


def toc_lua_files() -> list[str]:
    toc = ROOT / TOC_NAME
    if not toc.exists():
        fail(f"missing {TOC_NAME}")
        return []
    files = []
    for line in toc.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if raw.lower().endswith(".lua") and not raw.startswith("#"):
            files.append(raw.replace("\\", "/"))
    return files


def lint_toc() -> None:
    print("lint: toc")
    toc = ROOT / TOC_NAME
    text = toc.read_text(encoding="utf-8")
    if "## Interface: 30300" in text:
        ok("Interface 30300")
    else:
        fail("TOC must declare ## Interface: 30300")
    if "SavedVariablesPerCharacter: EdsCustomAddonDB" in text:
        ok("SavedVariablesPerCharacter declared")
    else:
        fail("missing SavedVariablesPerCharacter")

    files = toc_lua_files()
    expected = [
        "Core/Util.lua",
        "Core/Config.lua",
        "Core/Core.lua",
        "Core/UI.lua",
        "Modules/PartyXP/PartyXP.lua",
        "Sounds/manifest.lua",
        "Modules/Windfury/Windfury.lua",
        "Modules/BGSync/BGSync.lua",
    ]
    if files == expected:
        ok("TOC load order")
    else:
        fail(f"TOC load order {files} != {expected}")

    for rel in files:
        path = lua_file(rel)
        if path.exists():
            ok(f"exists {rel}")
        else:
            fail(f"missing {rel}")


def lint_lua_static() -> None:
    print("lint: static")
    for rel in toc_lua_files():
        path = lua_file(rel)
        text = path.read_text(encoding="utf-8")
        if "\t" in text:
            fail(f"{rel} contains tabs")
        else:
            ok(f"{rel} no tabs")
        for i, line in enumerate(text.splitlines(), 1):
            stripped = line.split("--", 1)[0]
            for pattern, reason in BANNED:
                if re.search(pattern, stripped):
                    fail(f"{rel}:{i}: {reason}")
    ui = (ROOT / "Core" / "UI.lua").read_text(encoding="utf-8")
    if "RegisterModule" in ui:
        fail("Core/UI.lua must not RegisterModule (panel is not a feature module)")
    else:
        ok("UI.lua is not a feature module")
    party = (ROOT / "Modules" / "PartyXP" / "PartyXP.lua").read_text(encoding="utf-8")
    if "RegisterModule" in party:
        ok("PartyXP registers itself")
    else:
        fail("PartyXP.lua does not call RegisterModule")
    windfury = (ROOT / "Modules" / "Windfury" / "Windfury.lua").read_text(encoding="utf-8")
    if "RegisterModule" in windfury:
        ok("Windfury registers itself")
    else:
        fail("Windfury.lua does not call RegisterModule")
    bgsync = (ROOT / "Modules" / "BGSync" / "BGSync.lua").read_text(encoding="utf-8")
    if "RegisterModule" in bgsync:
        ok("BGSync registers itself")
    else:
        fail("BGSync.lua does not call RegisterModule")


def lint_syntax(lua) -> None:
    print("lint: syntax")
    for rel in toc_lua_files():
        path = posix(lua_file(rel))
        try:
            lua.execute(f'assert(loadfile("{path}"))')
            ok(f"syntax {rel}")
        except Exception as exc:
            fail(f"syntax {rel}: {exc}")


def load_addon(lua, env_path: Path) -> None:
    lua.eval("dofile")(posix(env_path))
    for rel in toc_lua_files():
        lua.eval("dofile")(posix(lua_file(rel)))


def fire_loaded(lua) -> None:
    addon = lua.eval("EdsCustomAddon")
    addon.OnEvent(addon, "ADDON_LOADED", "Eds Custom Addon")


def last_sent(lua) -> list[str]:
    sent = lua.eval("wow.sent")
    out = []
    for i in range(1, len(sent) + 1):
        item = sent[i]
        msg = getattr(item, "msg", None)
        out.append(msg if msg is not None else str(item))
    return out


def last_sent_types(lua) -> list[str]:
    sent = lua.eval("wow.sent")
    out = []
    for i in range(1, len(sent) + 1):
        item = sent[i]
        out.append(getattr(item, "chatType", None))
    return out


def last_sent_entries(lua) -> list[dict]:
    sent = lua.eval("wow.sent")
    out = []
    for i in range(1, len(sent) + 1):
        item = sent[i]
        out.append({
            "msg": getattr(item, "msg", None),
            "chatType": getattr(item, "chatType", None),
            "target": getattr(item, "target", None),
        })
    return out


def set_battleground(lua, names: list[str], level: int = 41) -> None:
    wow = lua.eval("wow")
    wow.setBattleground(lua.table_from(names), level)


def set_friends(lua, names: list[str]) -> None:
    wow = lua.eval("wow")
    wow.setFriends(lua.table_from(names))


def last_sounds(lua) -> list[str]:
    sounds = lua.eval("wow.sounds")
    return [sounds[i] for i in range(1, len(sounds) + 1)]


def last_casts(lua) -> list[str]:
    casts = lua.eval("wow.casts")
    return [casts[i] for i in range(1, len(casts) + 1)]


def last_prints(lua) -> list[str]:
    prints = lua.eval("wow.prints")
    return [prints[i] for i in range(1, len(prints) + 1)]


def last_combat_text(lua) -> list[dict]:
    entries = lua.eval("wow.combatText")
    out = []
    for i in range(1, len(entries) + 1):
        entry = entries[i]
        out.append({
            "msg": entry.msg,
            "r": entry.r,
            "g": entry.g,
            "b": entry.b,
            "displayType": entry.displayType,
        })
    return out


def test_addon(lua) -> None:
    print("test: load + behavior")
    addon = lua.eval("EdsCustomAddon")
    wow = lua.eval("wow")

    fire_loaded(lua)
    if addon.loaded:
        ok("ADDON_LOADED initializes addon")
    else:
        fail("ADDON_LOADED did not set loaded")

    party = addon.GetModule(addon, "PartyXP")
    if party is None:
        fail("PartyXP not registered")
        return
    ok("PartyXP registered")

    if party.enabled:
        ok("PartyXP enabled by default")
    else:
        fail("PartyXP should default to enabled")

    if addon.ui is None:
        fail("CreateUI did not run")
    else:
        ok("ECA_Panel created")
        if addon.ui.shown:
            fail("panel should start hidden")
        else:
            ok("panel starts hidden")
        if addon.ui.windfuryPath:
            ok("panel has Windfury path box")
            box = addon.ui.windfuryPath
            box.SetText(box, "Interface\\AddOns\\Eds Custom Addon\\Sounds\\proc.wav")
            lost = box.scripts.OnEditFocusLost
            if lost:
                lost(box)
            path = addon.db.modules.Windfury.soundFile
            if path and "proc.wav" in path:
                ok("GUI sound path saves to db")
            else:
                fail(f"GUI path save got {path}")
        else:
            fail("panel missing windfuryPath edit box")
        if addon.ui.partyxpPause:
            ok("panel has PartyXP pause checkbox")
            wow.resetChat()
            wow.state.xpDisabled = False
            check = addon.ui.partyxpPause
            check.SetChecked(check, 1)
            check.scripts.OnClick(check)
            if addon.db.modules.PartyXP.paused:
                ok("GUI pause saves to db")
            else:
                fail("GUI pause did not set paused")
            sent = last_sent(lua)
            if sent == [".xp disable"]:
                ok("GUI pause disables XP")
            else:
                fail(f"GUI pause sent {sent}")
            check.SetChecked(check, None)
            check.scripts.OnClick(check)
            if not addon.db.modules.PartyXP.paused:
                ok("GUI unpause clears paused")
            else:
                fail("GUI unpause did not clear paused")
        else:
            fail("panel missing partyxpPause checkbox")
        if addon.ui.partyxpForce:
            ok("panel has PartyXP force checkbox")
            wow.resetChat()
            wow.setSolo()
            wow.state.xpDisabled = True
            force = addon.ui.partyxpForce
            force.SetChecked(force, 1)
            force.scripts.OnClick(force)
            if party.forceXP:
                ok("GUI force sets session flag")
            else:
                fail("GUI force did not set forceXP")
            sent = last_sent(lua)
            if sent == [".xp enable"]:
                ok("GUI force enables XP when solo")
            else:
                fail(f"GUI force sent {sent}")
            force.SetChecked(force, None)
            force.scripts.OnClick(force)
            if not party.forceXP:
                ok("GUI unforce clears session flag")
            else:
                fail("GUI unforce did not clear forceXP")
            wow.resetChat()
            wow.setSolo()
            wow.state.xpDisabled = True
            lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = true")
            addon.ui.partyxpPause.SetChecked(addon.ui.partyxpPause, 1)
            addon.ui.partyxpPause.scripts.OnClick(addon.ui.partyxpPause)
            force.SetChecked(force, 1)
            force.scripts.OnClick(force)
            if not addon.db.modules.PartyXP.paused and party.forceXP:
                ok("GUI force clears persisted pause")
            else:
                fail("force/pause not mutually exclusive")
            force.SetChecked(force, None)
            force.scripts.OnClick(force)
            lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = false")
        else:
            fail("panel missing partyxpForce checkbox")
        if addon.ui.windfuryTest:
            ok("panel has Windfury test button")
        else:
            fail("panel missing windfuryTest button")
        if addon.ui.windfuryProcPoolButtons:
            ok("panel has proc pool buttons")
            wow.resetChat()
            lua.execute("""
                WindfurySoundsKill = { [1] = "Sounds/kill-preview.mp3" }
                local wf = EdsCustomAddon:GetModule("Windfury")
                wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
                wf:SetPreviewProcPool("kill")
            """)
            addon.ui.windfuryTest.scripts.OnClick(addon.ui.windfuryTest)
            sounds = last_sounds(lua)
            if sounds and sounds[-1] == "Sounds/kill-preview.mp3":
                ok("Test proc uses selected kill pool")
            else:
                fail(f"Test proc pool play {sounds}")
            lua.execute("""
                local wf = EdsCustomAddon:GetModule("Windfury")
                wf.lastStreakProc = nil
                wf.streakCount = nil
                wf:SetPreviewProcPool("default")
            """)
            wow.resetChat()
        else:
            fail("panel missing windfuryProcPoolButtons")
        sound_rows = addon.ui.windfurySoundRows
        sound_test = addon.ui.windfurySoundTest
        if sound_rows and len(sound_rows) > 0 and sound_test:
            ok("panel has sound preview list")
            wow.resetChat()
            lua.execute(
                'local wf = EdsCustomAddon:GetModule("Windfury"); '
                "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil end"
            )
            sound_test.scripts.OnClick(sound_test)
            sounds = last_sounds(lua)
            manifest = lua.eval("WindfurySounds")
            if sounds and manifest and sounds[-1] == manifest[1]:
                ok("Test sound button plays selected manifest entry")
            else:
                fail(f"Test sound played {sounds}, expected {manifest[1] if manifest else None}")
            wow.resetChat()
            lua.execute(
                'local wf = EdsCustomAddon:GetModule("Windfury"); '
                "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil end"
            )
            sound_rows[2].scripts.OnClick(sound_rows[2])
            sound_test.scripts.OnClick(sound_test)
            sounds = last_sounds(lua)
            if sounds and manifest and sounds[-1] == manifest[2]:
                ok("Test sound button plays newly selected entry")
            else:
                fail(f"selected sound play {sounds}, expected {manifest[2] if manifest else None}")
        elif addon.ui.windfurySoundEmpty:
            ok("panel shows empty sound list message")
        else:
            fail("panel missing windfury sound list")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("solo sends .xp off")
    else:
        fail(f"solo sent {sent}, expected ['.xp disable']")
    types = last_sent_types(lua)
    if types == ["WHISPER"]:
        ok("alive sync uses WHISPER not SAY")
    else:
        fail(f"alive sync types {types}, expected ['WHISPER']")

    wow.resetChat()
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == []:
        ok("solo idempotent (no second .xp off)")
    else:
        fail(f"solo second sync sent {sent}")

    wow.resetChat()
    wow.setParty(True)
    wow.state.xpDisabled = True
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp enable"]:
        ok("online party member sends .xp on")
    else:
        fail(f"online party sent {sent}, expected ['.xp enable']")

    wow.resetChat()
    wow.setParty(False)
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("offline-only party sends .xp off")
    else:
        fail(f"offline party sent {sent}, expected ['.xp disable']")

    wow.resetChat()
    wow.setRaidSelfOnly()
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("raid of self only sends .xp off")
    else:
        fail(f"raid-self sent {sent}, expected ['.xp disable']")

    wow.resetChat()
    wow.setRaidWithPartner(True)
    wow.state.xpDisabled = True
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp enable"]:
        ok("raid with online partner sends .xp on")
    else:
        fail(f"raid-partner sent {sent}, expected ['.xp enable']")

    wow.resetChat()
    wow.setRaidWithPartner(False)
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("raid partner offline sends .xp off")
    else:
        fail(f"raid-offline-partner sent {sent}, expected ['.xp disable']")

    wow.resetChat()
    wow.state.ghost = True
    wow.setParty(False)
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    types = last_sent_types(lua)
    if sent == [".xp disable"] and types == ["WHISPER"] and wow.state.xpDisabled:
        ok("ghost party-leave still sends .xp off via WHISPER")
    else:
        fail(f"ghost whisper sent {sent} types {types} xpDisabled={wow.state.xpDisabled}")

    wow.resetChat()
    wow.state.playerName = ""
    wow.state.ghost = True
    wow.setSolo()
    wow.state.xpDisabled = False
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [] and not wow.state.xpDisabled:
        ok("ghost SAY fallback is dropped (no name, no group)")
    else:
        fail(f"ghost SAY-only sent {sent} xpDisabled={wow.state.xpDisabled}")

    wow.state.playerName = "Ed"
    wow.state.ghost = False
    wow.resetChat()
    addon.OnEvent(addon, "PLAYER_ALIVE")
    sent = last_sent(lua)
    if sent == []:
        ok("PLAYER_ALIVE is debounced")
    else:
        fail(f"PLAYER_ALIVE sent immediately {sent}")
    wow.flushDebounce()
    sent = last_sent(lua)
    types = last_sent_types(lua)
    if sent == [".xp disable"] and types == ["WHISPER"] and wow.state.xpDisabled:
        ok("PLAYER_ALIVE retries .xp off after rez")
    else:
        fail(f"PLAYER_ALIVE after tick sent {sent} types {types} xpDisabled={wow.state.xpDisabled}")

    addon.DisableModule(addon, "PartyXP")
    if not party.enabled:
        ok("DisableModule turns PartyXP off")
    else:
        fail("DisableModule left PartyXP enabled")
    wow.resetChat()
    wow.setParty(True)
    wow.state.xpDisabled = True
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == []:
        ok("disabled module does not send .xp")
    else:
        fail(f"disabled module sent {sent}")

    addon.EnableModule(addon, "partyxp")
    if party.enabled:
        ok("EnableModule is case-insensitive")
    else:
        fail("GetModule/EnableModule failed for 'partyxp'")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = False
    party.RequestSync(party)
    sent = last_sent(lua)
    if sent == []:
        ok("RequestSync is debounced (no immediate send)")
    else:
        fail(f"debounced sync sent immediately: {sent}")
    wow.flushDebounce()
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("debounce fires after 0.2s")
    else:
        fail(f"after tick sent {sent}, expected ['.xp disable']")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = False
    party.RequestSync(party)
    party.RequestSync(party)
    wow.flushDebounce()
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("burst RequestSync sends once")
    else:
        fail(f"burst debounce sent {sent}")

    db = lua.eval("EdsCustomAddonDB")
    if db.modules.PartyXP.enabled:
        ok("enabled state persisted to SavedVariables")
    else:
        fail("db.modules.PartyXP.enabled not true after EnableModule")

    addon.SlashHandler(addon, "debug")
    if addon.db.debug:
        ok("slash debug enables db.debug")
    else:
        fail("slash debug did not toggle on")

    shown_before = bool(addon.ui.shown)
    addon.SlashHandler(addon, "ui")
    if bool(addon.ui.shown) != shown_before:
        ok("slash ui toggles panel")
    else:
        fail("slash ui did not toggle panel visibility")
    addon.SlashHandler(addon, "ui")
    if bool(addon.ui.shown) == shown_before:
        ok("slash ui toggles panel back")
    else:
        fail("slash ui second toggle did not restore visibility")

    wow.resetChat()
    addon.SlashHandler(addon, "partyxp status")
    prints = last_prints(lua)
    if prints and "PartyXP" in prints[-1]:
        ok("slash partyxp status prints")
    else:
        fail(f"status prints {prints}")

    wow.resetChat()
    wow.setParty(True)
    wow.state.xpDisabled = False
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = true")
    party = lua.eval('EdsCustomAddon:GetModule("PartyXP")')
    party.SyncXP(party)
    sent = last_sent(lua)
    if sent == [".xp disable"]:
        ok("paused overrides party and disables XP")
    else:
        fail(f"paused party sent {sent}")

    wow.resetChat()
    wow.setParty(True)
    wow.state.xpDisabled = False
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = false")
    addon.SlashHandler(addon, "partyxp pause")
    sent = last_sent(lua)
    prints = last_prints(lua)
    if sent == [".xp disable"] and prints and "paused" in prints[-1].lower():
        ok("partyxp pause disables immediately")
    else:
        fail(f"partyxp pause sent {sent} prints {prints}")

    wow.resetChat()
    wow.setParty(True)
    wow.state.xpDisabled = True
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = false")
    addon.SlashHandler(addon, "partyxp unpause")
    sent = last_sent(lua)
    prints = last_prints(lua)
    if sent == [".xp enable"]:
        ok("unpause in party enables XP")
    else:
        fail(f"unpause sent {sent}")
    if prints and "unpaused" in prints[-1] and "wantXP=on" in prints[-1]:
        ok("unpause prints wantXP=on when partner online")
    else:
        fail(f"unpause status prints {prints}")

    wow.resetChat()
    wow.setParty(False)
    wow.state.xpDisabled = True
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = true")
    addon.SlashHandler(addon, "partyxp unpause")
    sent = last_sent(lua)
    prints = last_prints(lua)
    if sent == []:
        ok("unpause with offline party sends nothing when XP already off")
    else:
        fail(f"offline party unpause sent {sent}")
    if prints and "wantXP=off" in prints[-1]:
        ok("unpause explains wantXP=off for offline party")
    else:
        fail(f"offline unpause status prints {prints}")

    wow.resetChat()
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = true")
    addon.SlashHandler(addon, "partyxp status")
    prints = last_prints(lua)
    if prints and "paused=yes" in prints[-1]:
        ok("partyxp status shows paused=yes")
    else:
        fail(f"paused status prints {prints}")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = True
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = false")
    party = lua.eval('EdsCustomAddon:GetModule("PartyXP")')
    party.SetForceXP(party, True)
    sent = last_sent(lua)
    if sent == [".xp enable"]:
        ok("force overrides solo and enables XP")
    else:
        fail(f"force solo sent {sent}")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = True
    party.SetForceXP(party, False)
    addon.SlashHandler(addon, "partyxp force")
    prints = last_prints(lua)
    sent = last_sent(lua)
    if prints and "forcing" in prints[-1].lower() and sent == [".xp enable"]:
        ok("partyxp force slash enables XP")
    else:
        fail(f"partyxp force sent {sent} prints {prints}")

    wow.resetChat()
    wow.setSolo()
    wow.state.xpDisabled = False
    party.SetForceXP(party, True)
    wow.resetChat()
    addon.SlashHandler(addon, "partyxp unforce")
    sent = last_sent(lua)
    prints = last_prints(lua)
    if sent == [".xp disable"] and prints and "force released" in prints[-1]:
        ok("partyxp unforce restores solo XP off")
    else:
        fail(f"partyxp unforce sent {sent} prints {prints}")

    wow.resetChat()
    party.SetForceXP(party, True)
    addon.SlashHandler(addon, "partyxp status")
    prints = last_prints(lua)
    if prints and "force=yes" in prints[-1]:
        ok("partyxp status shows force=yes")
    else:
        fail(f"force status prints {prints}")
    party.SetForceXP(party, False)
    lua.execute("EdsCustomAddon.db.modules.PartyXP.paused = false")

    wow.resetChat()
    lua.execute((ROOT / "Sounds" / "manifest.lua").read_text(encoding="utf-8"))
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.lastStreakProc = nil; wf.streakCount = nil; wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil end"
    )
    addon.SlashHandler(addon, "windfury test")
    sounds = last_sounds(lua)
    if sounds:
        ok("windfury test plays sound file")
    else:
        fail(f"windfury test sounds {sounds}")
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[0]["msg"] == "WINDFURY":
        ok("windfury test shows WINDFURY combat text")
    else:
        fail(f"windfury test combat text {combat}")
    prints = last_prints(lua)
    joined = " ".join(prints)
    if "PlaySoundFile" in joined:
        ok("windfury test debug-logs PlaySoundFile")
    else:
        fail(f"windfury test debug prints {prints}")
    if "CombatText WINDFURY" in joined:
        ok("windfury test debug-logs CombatText")
    else:
        fail(f"windfury test combat debug prints {prints}")

    addon.SlashHandler(addon, "windfury test")
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[-1]["msg"] == "WINDFURY x2":
        ok("second windfury test shows WINDFURY x2")
    else:
        fail(f"second windfury test combat text {combat}")
    if len(combat) == 1:
        ok("streak combat text replaces previous WINDFURY")
    else:
        fail(f"streak combat text stacked {combat}")

    lua.execute("""
        WindfurySounds = {
            [1] = "Sounds/default.mp3",
        }
        WindfurySoundsLowHp = {
            [1] = "Sounds/lowhp-bruh.mp3",
        }
        WindfurySoundsKill = {
            [1] = "Sounds/kill-wilhelm.mp3",
        }
    """)
    lowhp_list = lua.eval("WindfurySoundsLowHp")
    kill_list = lua.eval("WindfurySoundsKill")
    if lowhp_list and "lowhp-" in lowhp_list[1]:
        ok("manifest lowhp pool uses lowhp- prefix")
    else:
        fail(f"lowhp pool {lowhp_list}")
    if kill_list and "kill-" in kill_list[1]:
        ok("manifest kill pool uses kill- prefix")
    else:
        fail(f"kill pool {kill_list}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil; "
        "wf.lastStreakProc = nil; wf.streakCount = nil end"
    )
    me = lua.eval("wow.state.playerGUID")
    mob = "0x0000000000000002"
    lua.execute(f'wow.state.targetGUID = "{mob}"')
    lua.execute("wow.state.targetHealth = 10")
    lua.execute("wow.state.targetHealthMax = 1000")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        50,
        0,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if played and played[-1] == "Sounds/lowhp-bruh.mp3":
        ok("WF lowhp pool plays when target below threshold")
    else:
        fail(f"WF lowhp sound {played}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil; "
        "wf.lastStreakProc = nil; wf.streakCount = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        50,
        0,
    )
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[0]["msg"] == "WINDFURY":
        ok("WF SPELL_DAMAGE alone shows WINDFURY combat text")
    else:
        fail(f"WF damage-only combat text {combat}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    lua.execute("wow.state.targetHealth = 10")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        50,
        0,
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        500,
        200,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if len(played) == 1 and played[-1] == "Sounds/kill-wilhelm.mp3":
        ok("WF kill wins over lowhp in same proc burst")
    else:
        fail(f"WF kill+lowhp burst sound {played}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        500,
        200,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if played and played[-1] == "Sounds/kill-wilhelm.mp3":
        ok("WF kill pool plays on overkill")
    else:
        fail(f"WF kill sound {played}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    lua.execute(f'wow.state.targetGUID = "{mob}"')
    lua.execute("wow.state.targetHealth = 0")
    lua.execute("wow.state.targetHealthMax = 1000")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        500,
        0,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if played and played[-1] == "Sounds/kill-wilhelm.mp3":
        ok("WF kill pool plays when target dies without overkill")
    else:
        fail(f"WF kill without overkill sound {played}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    lua.execute("wow.state.targetHealth = 900")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        100,
        0,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if played and played[-1] == "Sounds/default.mp3":
        ok("WF default pool plays on normal hit")
    else:
        fail(f"WF default damage sound {played}")

    wow.resetChat()
    lua.execute("""
        WindfurySoundsKill = {}
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
        wf.procBurstActive = nil
        wf.procBurstCategory = nil
    """)
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        100,
        50,
    )
    wow.flushDebounce()
    played = last_sounds(lua)
    if played and played[-1] == "Sounds/default.mp3":
        ok("WF kill category falls back to default when kill pool empty")
    else:
        fail(f"WF kill fallback sound {played}")

    lua.execute((ROOT / "Sounds" / "manifest.lua").read_text(encoding="utf-8"))
    sound_list = lua.eval("WindfurySounds")
    sound_count = len(sound_list)
    if sound_count > 0:
        pick = min(2, sound_count)
        lua.execute(f"""
            math.random = function() return {pick} end
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.recentSounds = nil
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
        """)
        wow.resetChat()
        wf = lua.eval('EdsCustomAddon:GetModule("Windfury")')
        wf.Play(wf)
        played = last_sounds(lua)
        expected = sound_list[pick]
        if played and played[-1] == expected:
            ok("Play picks random manifest sound")
        else:
            fail(f"manifest play {played} expected {expected}")

        durations = lua.eval("WindfurySoundDurations")
        duration_ok = lua.eval("""
            (function()
                if type(WindfurySoundDurations) ~= "table" then
                    return false
                end
                local n = 0
                for path, seconds in pairs(WindfurySoundDurations) do
                    if type(path) ~= "string" or type(seconds) ~= "number" or seconds <= 0 then
                        return false
                    end
                    n = n + 1
                end
                return n > 0
            end)()
        """)
        if duration_ok:
            ok("manifest has WindfurySoundDurations entries")
        else:
            fail(f"manifest missing or invalid WindfurySoundDurations {durations}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
                [2] = "Sounds/b.mp3",
                [3] = "Sounds/c.mp3",
            }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
                ["Sounds/b.mp3"] = 2.0,
                ["Sounds/c.mp3"] = 2.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.recentSounds = nil
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play()
            wf:Play()
        """)
        played = last_sounds(lua)
        if len(played) == 1:
            ok("duration lock skips overlapping Play")
        else:
            fail(f"duration lock overlap {played}")
        prints = last_prints(lua)
        if any("busy" in p for p in prints):
            ok("duration lock debug-logs busy skip")
        else:
            fail(f"duration lock busy debug {prints}")

        wow.resetChat()
        lua.execute("""
            local wf = EdsCustomAddon:GetModule("Windfury")
            wow.time = wow.time + 2.1
            wf:Play()
        """)
        played = last_sounds(lua)
        if len(played) == 1:
            ok("duration lock allows Play after clip ends")
        else:
            fail(f"duration lock after wait {played}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
                [2] = "Sounds/b.mp3",
                [3] = "Sounds/c.mp3",
            }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            wf:PreviewSound("Sounds/a.mp3")
            wf:PreviewSound("Sounds/b.mp3")
        """)
        played = last_sounds(lua)
        if played == ["Sounds/a.mp3"]:
            ok("PreviewSound respects duration lock")
        else:
            fail(f"PreviewSound lock {played}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
            }
            WindfurySoundsKill = {
                [1] = "Sounds/kill-x.mp3",
            }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
                ["Sounds/kill-x.mp3"] = 3.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play("default")
            wf:Play("kill")
        """)
        played = last_sounds(lua)
        if played == ["Sounds/a.mp3", "Sounds/kill-x.mp3"]:
            ok("kill overrides non-kill duration lock")
        else:
            fail(f"kill override {played}")
        prints = last_prints(lua)
        if any("kill overrides" in p for p in prints):
            ok("kill override debug-logs")
        else:
            fail(f"kill override debug {prints}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
            }
            WindfurySoundsKill = {
                [1] = "Sounds/kill-x.mp3",
            }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
                ["Sounds/kill-x.mp3"] = 3.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play("kill")
            wf:Play("kill")
        """)
        played = last_sounds(lua)
        if played == ["Sounds/kill-x.mp3"]:
            ok("kill does not override active kill lock")
        else:
            fail(f"kill vs kill lock {played}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
            }
            WindfurySoundsKill = {
                [1] = "Sounds/kill-x.mp3",
            }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
                ["Sounds/kill-x.mp3"] = 3.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play("kill")
            wf:Play("default")
        """)
        played = last_sounds(lua)
        if played == ["Sounds/kill-x.mp3"]:
            ok("default does not override active kill lock")
        else:
            fail(f"default vs kill lock {played}")

        wow.resetChat()
        lua.execute("""
            wow.state.cvars.Sound_MusicVolume = "1"
            WindfurySounds = { [1] = "Sounds/a.mp3" }
            WindfurySoundDurations = { ["Sounds/a.mp3"] = 2.0 }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            EdsCustomAddon.db.modules.Windfury.musicDuck = { active = false, saved = nil }
            math.random = function() return 1 end
            wf:Play()
        """)
        vol = lua.eval('tonumber(GetCVar("Sound_MusicVolume"))')
        if vol == 0.25:
            ok("WF play ducks music volume")
        else:
            fail(f"music duck vol {vol}")

        wow.resetChat()
        lua.execute("""
            wow.state.cvars.Sound_MusicVolume = "1"
            WindfurySounds = { [1] = "Sounds/a.mp3" }
            WindfurySoundsKill = { [1] = "Sounds/kill-x.mp3" }
            WindfurySoundDurations = {
                ["Sounds/a.mp3"] = 2.0,
                ["Sounds/kill-x.mp3"] = 3.0,
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            EdsCustomAddon.db.modules.Windfury.musicDuck = { active = false, saved = nil }
            math.random = function() return 1 end
            wf:Play("default")
            wf:Play("kill")
        """)
        saved = lua.eval("EdsCustomAddon.db.modules.Windfury.musicDuck.saved")
        vol = lua.eval('tonumber(GetCVar("Sound_MusicVolume"))')
        if saved == "1" and vol == 0.25:
            ok("WF music duck keeps original across overlapping play")
        else:
            fail(f"music duck saved={saved} vol={vol}")

        wow.resetChat()
        lua.execute("""
            wow.state.cvars.Sound_MusicVolume = "1"
            WindfurySounds = { [1] = "Sounds/a.mp3" }
            WindfurySoundDurations = { ["Sounds/a.mp3"] = 2.0 }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            EdsCustomAddon.db.modules.Windfury.musicDuck = { active = false, saved = nil }
            math.random = function() return 1 end
            wf:Play()
            wow.time = wow.time + 2.1
            wow.tick(0.05)
        """)
        vol = lua.eval('tonumber(GetCVar("Sound_MusicVolume"))')
        active = lua.eval("EdsCustomAddon.db.modules.Windfury.musicDuck.active")
        if active and vol is not None and vol < 1:
            ok("WF music still fading after clip duration")
        else:
            fail(f"music mid-fade vol={vol} active={active}")
        lua.execute("wow.tick(0.8)")
        vol = lua.eval('tonumber(GetCVar("Sound_MusicVolume"))')
        active = lua.eval("EdsCustomAddon.db.modules.Windfury.musicDuck.active")
        if vol == 1 and not active:
            ok("WF music fades back after clip duration")
        else:
            fail(f"music fade restore vol={vol} active={active}")

        wow.resetChat()
        lua.execute("""
            wow.state.cvars.Sound_MusicVolume = "0.8"
            WindfurySounds = { [1] = "Sounds/a.mp3" }
            WindfurySoundDurations = { ["Sounds/a.mp3"] = 5.0 }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            EdsCustomAddon.db.modules.Windfury.musicDuck = { active = false, saved = nil }
            math.random = function() return 1 end
            wf:Play()
            wf:Disable()
        """)
        vol = lua.eval('tonumber(GetCVar("Sound_MusicVolume"))')
        active = lua.eval("EdsCustomAddon.db.modules.Windfury.musicDuck.active")
        if vol == 0.8 and not active:
            ok("WF Disable restores music volume")
        else:
            fail(f"Disable music restore vol={vol} active={active}")
        lua.execute("""
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf:Enable()
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            EdsCustomAddon.db.modules.Windfury.musicDuck = { active = false, saved = nil }
        """)

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
                [2] = "Sounds/b.mp3",
                [3] = "Sounds/c.mp3",
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.recentSounds = nil
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play()
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            wf:Play()
        """)
        played = last_sounds(lua)
        if len(played) == 2 and played[0] != played[1]:
            ok("shuffle avoids immediate repeat")
        else:
            fail(f"shuffle immediate repeat {played}")

        wow.resetChat()
        lua.execute("""
            WindfurySounds = {
                [1] = "Sounds/a.mp3",
                [2] = "Sounds/b.mp3",
                [3] = "Sounds/c.mp3",
            }
            local wf = EdsCustomAddon:GetModule("Windfury")
            wf.recentSounds = nil
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            math.random = function() return 1 end
            wf:Play()
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            wf:Play()
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            wf:Play()
            wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil
            wf:Play()
        """)
        played = last_sounds(lua)
        if played == [
            "Sounds/a.mp3",
            "Sounds/b.mp3",
            "Sounds/c.mp3",
            "Sounds/a.mp3",
        ]:
            ok("shuffle cycles after small library exhausted")
        else:
            fail(f"shuffle cycle sequence {played}")

        manifest_restore = (ROOT / "Sounds" / "manifest.lua").read_text(encoding="utf-8")
        lua.execute(manifest_restore)

        shuffle_ok = lua.eval("""
            (function()
                WindfurySounds = {
                    [1] = "Sounds/s01.mp3",
                    [2] = "Sounds/s02.mp3",
                    [3] = "Sounds/s03.mp3",
                    [4] = "Sounds/s04.mp3",
                    [5] = "Sounds/s05.mp3",
                    [6] = "Sounds/s06.mp3",
                    [7] = "Sounds/s07.mp3",
                    [8] = "Sounds/s08.mp3",
                    [9] = "Sounds/s09.mp3",
                    [10] = "Sounds/s10.mp3",
                    [11] = "Sounds/s11.mp3",
                }
                WindfurySoundsLowHp = {}
                WindfurySoundsKill = {}
                local wf = EdsCustomAddon:GetModule("Windfury")
                wf.recentSounds = nil
                local count = #WindfurySounds
                local window = math.min(count - 1, 10)
                local ri = 0
                math.random = function(max)
                    ri = ri + 1
                    return ((ri - 1) % max) + 1
                end
                local picks = {}
                for i = 1, count + 1 do
                    picks[i] = wf:PickSoundPath()
                end
                local i = count + 1
                local blocked = {}
                for j = i - window, i - 1 do
                    blocked[picks[j]] = true
                end
                return not blocked[picks[i]]
            end)()
        """)
        if shuffle_ok:
            ok("shuffle avoids repeat within dynamic window")
        else:
            fail("shuffle pick repeated within dynamic window")

        ten_pool_ok = lua.eval("""
            (function()
                WindfurySounds = {
                    [1] = "Sounds/t01.mp3",
                    [2] = "Sounds/t02.mp3",
                    [3] = "Sounds/t03.mp3",
                    [4] = "Sounds/t04.mp3",
                    [5] = "Sounds/t05.mp3",
                    [6] = "Sounds/t06.mp3",
                    [7] = "Sounds/t07.mp3",
                    [8] = "Sounds/t08.mp3",
                    [9] = "Sounds/t09.mp3",
                    [10] = "Sounds/t10.mp3",
                }
                WindfurySoundsLowHp = {}
                WindfurySoundsKill = {}
                local wf = EdsCustomAddon:GetModule("Windfury")
                wf.recentSounds = nil
                local count = #WindfurySounds
                local window = math.min(count - 1, 10)
                local ri = 0
                math.random = function(max)
                    ri = ri + 1
                    return ((ri - 1) % max) + 1
                end
                local picks = {}
                for i = 1, count + 1 do
                    picks[i] = wf:PickSoundPath()
                end
                local i = count + 1
                local blocked = {}
                for j = i - window, i - 1 do
                    blocked[picks[j]] = true
                end
                return not blocked[picks[i]]
            end)()
        """)
        if ten_pool_ok:
            ok("shuffle 10-sound pool avoids repeat on 11th pick")
        else:
            fail("shuffle 10-sound pool repeated within window")
    else:
        ok("Play uses fallback path when manifest empty")

    wow.resetInventory()
    wf = lua.eval('EdsCustomAddon:GetModule("Windfury")')
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and alert.shown:
        ok("WF alert shows when dual wield missing enchants")
    else:
        fail("WF alert hidden for dual wield without WF")
    label = lua.eval("ECA_WindfuryAlert.label:GetText()")
    if label == "RECAST WINDFURY (x2)":
        ok("WF alert shows (x2) when both weapons need Windfury")
    else:
        fail(f"WF alert dual wield label {label}")

    wow.resetInventory()
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when both weapons have Windfury")
    else:
        fail(f"WF alert shown with both WF {alert}")

    lua.execute("""
        wow.state.weaponEnchantStale = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when stale API but tooltip shows Windfury")
    else:
        fail(f"WF alert false positive on stale API {alert}")

    lua.execute("""
        wow.state.weaponEnchantStale = true
        wow.state.tooltipHideEnchant = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime()
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden during zone-load grace with incomplete data")
    else:
        fail(f"WF alert shown during grace {alert}")

    lua.execute("""
        wow.state.weaponEnchantStale = false
        wow.state.tooltipHideEnchant = false
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and alert.shown:
        ok("WF alert shows after grace when Windfury truly missing")
    else:
        fail(f"WF alert hidden after grace with missing WF {alert}")

    lua.execute("""
        wow.state.itemInfoDelayed = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden while item info is uncached")
    else:
        fail(f"WF alert shown with uncached item info {alert}")
    lua.execute("wow.state.itemInfoDelayed = false")

    lua.execute("""
        wow.state.weaponEnchantStale = true
        wow.state.tooltipHideEnchant = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    wf.OnEvent(wf, "PLAYER_ENTERING_WORLD")
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden on zone load with stale enchant data")
    else:
        fail(f"WF alert shown on zone load {alert}")

    lua.execute("""
        wow.state.weaponEnchantStale = false
        wow.state.tooltipHideEnchant = false
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
    """)
    wf.OnEvent(wf, "PLAYER_REGEN_DISABLED")
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden after combat entry once enchant data loads")
    else:
        fail(f"WF alert shown after combat entry {alert}")

    lua.execute("""
        wow.state.weaponEnchantStale = true
        wow.state.tooltipHideEnchant = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    wf.OnEvent(wf, "PLAYER_ENTERING_WORLD")
    lua.execute("""
        wow.state.weaponEnchantStale = false
        wow.state.tooltipHideEnchant = false
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
    """)
    lua.execute("wow.tick(0.6)")
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert recheck after zone load clears false positive")
    else:
        fail(f"WF alert still shown after deferred recheck {alert}")

    wow.resetInventory()
    lua.execute("""
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            tooltipMinimal = true,
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when API has enchant but AH tooltip is incomplete")
    else:
        fail(f"WF alert false positive on AH-like tooltip {alert}")

    wow.resetInventory()
    lua.execute("""
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Flametongue IX",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when main hand has Flametongue")
    else:
        fail(f"WF alert shown with Flametongue {alert}")
    remembered = lua.eval(
        'EdsCustomAddon.db.modules.Windfury.slotImbue.main'
    )
    if remembered == "flametongue":
        ok("WF remembers Flametongue on main hand")
    else:
        fail(f"slotImbue.main {remembered}")

    wow.resetInventory()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf:GetSlotImbueDb().main = "windfury"
        wf:GetSlotImbueDb().off = "windfury"
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Rockbiter IV",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when main hand has Rockbiter")
    else:
        fail(f"WF alert shown with Rockbiter {alert}")

    wow.resetInventory()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.off = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.state.weaponEnchants.offExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Flametongue IX",
        })
        wf:UpdateAlert()
    """)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden for Windfury main and Flametongue off")
    else:
        fail(f"WF alert shown for WF+FT {alert}")

    wow.resetInventory()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
        wf:GetSlotImbueDb().main = "windfury"
        wf:GetSlotImbueDb().off = "flametongue"
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Flametongue IX",
        })
        wf:UpdateAlert()
    """)
    alert = lua.eval("ECA_WindfuryAlert")
    label = lua.eval("ECA_WindfuryAlert and ECA_WindfuryAlert.label:GetText()")
    if alert and alert.shown and label == "RECAST WINDFURY":
        ok("WF alert recasts Windfury only when off hand still has Flametongue")
    else:
        fail(f"mixed missing alert shown={getattr(alert, 'shown', None)} label={label}")
    wow.resetChat()
    lua.execute("ECA_WindfuryAlertCast:Click()")
    casts = last_casts(lua)
    if casts == ["Windfury Weapon"]:
        ok("WF alert click casts remembered main-hand imbue")
    else:
        fail(f"alert click casts {casts}")

    wow.resetInventory()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
        wf:GetSlotImbueDb().main = "windfury"
        wf:GetSlotImbueDb().off = "flametongue"
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
        })
        wf:UpdateAlert()
    """)
    label = lua.eval("ECA_WindfuryAlert.label:GetText()")
    if label == "RECAST WINDFURY":
        ok("WF alert prefers main-hand recast when both imbues missing")
    else:
        fail(f"both-missing mixed label {label}")
    wow.resetChat()
    lua.execute("ECA_WindfuryAlertCast:Click()")
    casts = last_casts(lua)
    if casts == ["Windfury Weapon"]:
        ok("WF alert click casts main-hand spell first when both missing")
    else:
        fail(f"both-missing click casts {casts}")

    wow.resetInventory()
    wow.resetChat()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
        wf.expiryWarned = {}
        wf.lastRemaining = {}
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            enchantExpirationMs = 1800000,
        })
        wow.setInventorySlot(17, {
            link = "|cff9d9d9d|Hitem:17:0:0:0:0:0:0:0|h[Mace]|h|r",
            name = "Mace",
            itemType = "Weapon",
            subType = "Mace",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Flametongue IX",
            enchantExpirationMs = 45000,
        })
        wf:CheckEnchantExpiry()
    """)
    combat = last_combat_text(lua)
    if combat and combat[-1]["msg"] == "RECAST FLAMETONGUE (off hand)":
        ok("WF expiry uses Flametongue text for off-hand imbue")
    else:
        fail(f"FT expiry combat text {combat}")

    lua.execute("""
        EdsCustomAddon.db.modules.Windfury.slotImbue.main = "windfury"
        EdsCustomAddon.db.modules.Windfury.slotImbue.off = "windfury"
    """)

    wow.resetInventory()
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            tooltipMinimal = true,
        })
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden when only weapon name visible on tooltip")
    else:
        fail(f"WF alert shown with incomplete tooltip {alert}")

    wow.resetInventory()
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
        })
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.lastZoneLoad = GetTime() - 5
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and alert.shown:
        ok("WF alert shown before Windfury cast when imbue missing")
    else:
        fail(f"WF alert not shown before cast test {alert}")

    lua.execute("""
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    me = lua.eval("wow.state.playerGUID")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_CAST_SUCCESS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        8232,
        "Windfury Weapon",
        1,
        2,
    )
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden after Windfury cast success")
    else:
        fail(f"WF alert still shown after cast {alert}")

    wow.resetInventory()
    lua.execute("""
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 1800000
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            tooltipMinimal = true,
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden before AH close recheck with active Windfury")
    else:
        fail(f"WF alert shown before AH close {alert}")

    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            tooltipMinimal = false,
        })
    """)
    wf.OnEvent(wf, "AUCTION_HOUSE_CLOSED")
    lua.execute("wow.tick(0.6)")
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert recheck after AH close clears stale state")
    else:
        fail(f"WF alert still shown after AH close {alert}")

    wow.resetInventory()
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Pole]|h|r",
            name = "Strong Fishing Pole",
            itemType = "Weapon",
            subType = "Fishing Pole",
            equipLoc = "INVTYPE_2HWEAPON",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden while holding fishing pole")
    else:
        fail("WF alert shown for fishing pole")

    wow.resetInventory()
    lua.execute("""
        wow.state.playerClass = "WARRIOR"
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_2HWEAPON",
        })
    """)
    wf.UpdateAlert(wf)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hidden for non-shaman")
    else:
        fail("WF alert shown for warrior")
    lua.execute('wow.state.playerClass = "SHAMAN"')

    if addon.ui.windfuryAlertMove:
        ok("panel has Move NO WF badge checkbox")
    else:
        fail("panel missing windfuryAlertMove checkbox")

    if addon.ui.windfuryAlertFontSize:
        ok("panel has NO WF font size box")
    else:
        fail("panel missing windfuryAlertFontSize edit box")

    wf.SaveAlertFontSize(wf, "18")
    wf.ApplyAlertFont(wf)
    cfg = lua.eval("EdsCustomAddon.db.modules.Windfury.alert")
    alert = lua.eval("ECA_WindfuryAlert")
    if cfg and cfg.fontSize == 18:
        ok("WF alert font size saves to db")
    else:
        fail(f"WF alert font size save got {cfg}")
    if alert and alert.height == 32:
        ok("WF alert frame resizes for larger font")
    else:
        fail(f"WF alert frame height {getattr(alert, 'height', alert)}")

    wow.resetInventory()
    lua.execute("""
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
        })
    """)
    wf.SetAlertMove(wf, True)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and alert.shown:
        ok("WF alert visible in move mode even with Windfury active")
    else:
        fail("WF alert not shown for reposition mode")
    cast_shown = lua.eval("ECA_WindfuryAlertCast and ECA_WindfuryAlertCast.shown")
    cast_type = lua.eval('ECA_WindfuryAlertCast and ECA_WindfuryAlertCast:GetAttribute("type")')
    if not cast_shown and not cast_type:
        ok("WF cast overlay hidden in move mode")
    else:
        fail(f"cast overlay in move mode shown={cast_shown} type={cast_type}")

    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        local frame = wf.alertFrame
        frame:ClearAllPoints()
        frame:SetPoint("CENTER", UIParent, "CENTER", 12, -34)
        wf:SaveAlertPosition()
    """)
    cfg = lua.eval("EdsCustomAddon.db.modules.Windfury.alert")
    if cfg and cfg.point == "CENTER" and cfg.x == 12 and cfg.y == -34:
        ok("WF alert position saves to db")
    else:
        fail(f"WF alert position save got {cfg}")

    wf.SetAlertMove(wf, False)
    alert = lua.eval("ECA_WindfuryAlert")
    if alert and not alert.shown:
        ok("WF alert hides after move mode off when Windfury active")
    else:
        fail("WF alert still shown after move mode off")

    wow.resetChat()
    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.expiryWarned = {}
        wf.lastRemaining = {}
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            enchantExpirationMs = 45000,
        })
        wf:CheckEnchantExpiry()
    """)
    combat = last_combat_text(lua)
    if combat and combat[-1]["msg"] == "RECAST WINDFURY":
        ok("WF expiry shows RECAST WINDFURY combat text")
    else:
        fail(f"WF expiry combat text {combat}")
    wf.CheckEnchantExpiry(wf)
    combat = last_combat_text(lua)
    if len(combat) == 1:
        ok("WF expiry warning fires once per enchant")
    else:
        fail(f"WF expiry repeated {combat}")

    lua.execute("""
        local wf = EdsCustomAddon:GetModule("Windfury")
        wf.expiryWarned = { [16] = true }
        wf.lastRemaining = { [16] = 45 }
        wow.state.weaponEnchants.main = true
        wow.state.weaponEnchants.mainExp = 45000
        wow.state.tooltipHideEnchant = true
        wow.setInventorySlot(16, {
            link = "|cff9d9d9d|Hitem:16:0:0:0:0:0:0:0|h[Axe]|h|r",
            name = "Axe",
            itemType = "Weapon",
            subType = "Axe",
            equipLoc = "INVTYPE_WEAPON",
            enchantText = "Windfury VIII",
            enchantExpirationMs = 45000,
        })
        wf:CheckEnchantExpiry()
    """)
    expiry_preserved = lua.eval(
        'EdsCustomAddon:GetModule("Windfury").expiryWarned[16] and true or false'
    )
    if expiry_preserved:
        ok("WF expiry state preserved when SlotHasWindfury is nil")
    else:
        fail("WF expiry state cleared on uncertain enchant data")
    lua.execute("wow.state.tooltipHideEnchant = false")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.lastStreakProc = nil; wf.streakCount = nil; wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; "
        "wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    me = lua.eval("wow.state.playerGUID")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    wow.flushDebounce()
    sounds = last_sounds(lua)
    if len(sounds) == 1:
        ok("player Windfury EXTRA_ATTACKS plays once")
    else:
        fail(f"WF proc sounds {sounds}")
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[0]["msg"] == "WINDFURY":
        ok("player Windfury EXTRA_ATTACKS shows WINDFURY once")
    else:
        fail(f"WF proc combat text {combat}")
    prints = last_prints(lua)
    joined = " ".join(prints)
    if "cleu sub=SPELL_EXTRA_ATTACKS" in joined and "match=yes" in joined and "proc -> play default" in joined:
        ok("windfury proc debug-logs cleu match and play")
    else:
        fail(f"WF proc debug prints {prints}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.lastStreakProc = nil; wf.streakCount = nil; wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; "
        "wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    sounds = last_sounds(lua)
    if sounds == []:
        ok("Windfury proc sound waits for fallback debounce")
    else:
        fail(f"immediate WF sound played before fallback {sounds}")
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[0]["msg"] == "WINDFURY":
        ok("Windfury EXTRA_ATTACKS shows combat text before fallback")
    else:
        fail(f"WF combat text missing before fallback {combat}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    wow.flushDebounce()
    sounds = last_sounds(lua)
    if len(sounds) == 1:
        ok("Windfury EXTRA_ATTACKS fallback plays default sound")
    else:
        fail(f"WF fallback sound {sounds}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.lastStreakProc = nil; wf.streakCount = nil; wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; "
        "wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    lua.execute("wow.state.targetHealth = 900")
    lua.execute("wow.state.targetHealthMax = 1000")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_DAMAGE",
        me,
        "Ed",
        0,
        mob,
        "Mob",
        0,
        25504,
        "Windfury Attack",
        1,
        100,
        0,
    )
    wow.flushDebounce()
    sounds = last_sounds(lua)
    if len(sounds) == 1:
        ok("WF proc burst coalesces multiple CLEU into one sound")
    else:
        fail(f"WF burst coalescing played {sounds}")

    wow.resetChat()
    lua.execute(
        'local wf = EdsCustomAddon:GetModule("Windfury"); '
        "if wf then wf.lastStreakProc = nil; wf.streakCount = nil; wf.soundBusyUntil = nil; wf.soundBusyIsKill = nil; "
        "wf.procBurstActive = nil; wf.procBurstCategory = nil end"
    )
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    lua.execute("wow.time = wow.time + 0.2")
    wow.flushDebounce()
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    wow.flushDebounce()
    combat = last_combat_text(lua)
    if len(combat) == 1 and combat[0]["msg"] == "WINDFURY x2":
        ok("consecutive Windfury within 5s shows x2")
    else:
        fail(f"WF streak x2 combat text {combat}")

    lua.execute("wow.time = wow.time + 6")
    wow.flushDebounce()
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        me,
        "Ed",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    combat = last_combat_text(lua)
    if combat and combat[-1]["msg"] == "WINDFURY":
        ok("Windfury streak resets after 5s")
    else:
        fail(f"WF streak reset combat text {combat}")

    wow.resetChat()
    lua.eval("wow.time")  # keep lupa warm
    lua.execute("wow.time = wow.time + 1")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SPELL_EXTRA_ATTACKS",
        "0xDEAD",
        "Namepoc",
        0,
        me,
        "Ed",
        0,
        25505,
        "Windfury Weapon",
        1,
        2,
    )
    sounds = last_sounds(lua)
    if sounds == []:
        ok("other player's Windfury does not play")
    else:
        fail(f"other WF played {sounds}")
    combat = last_combat_text(lua)
    if combat == []:
        ok("other player's Windfury does not show combat text")
    else:
        fail(f"other WF combat text {combat}")
    prints = last_prints(lua)
    if not any("Windfury:" in p for p in prints):
        ok("other player's Windfury does not debug-log")
    else:
        fail(f"other WF debug prints {prints}")

    wow.resetChat()
    lua.execute("wow.time = wow.time + 1")
    addon.OnEvent(
        addon,
        "COMBAT_LOG_EVENT_UNFILTERED",
        0,
        "SWING_DAMAGE",
        me,
        "Ed",
        0,
        "0x2",
        "Mob",
        0,
    )
    sounds = last_sounds(lua)
    if sounds == []:
        ok("swing damage does not play Windfury sound")
    else:
        fail(f"swing played {sounds}")
    combat = last_combat_text(lua)
    if combat == []:
        ok("swing damage does not show Windfury combat text")
    else:
        fail(f"swing combat text {combat}")

    wow.resetChat()
    addon.SlashHandler(addon, "nope")
    prints = last_prints(lua)
    if prints and "unknown command" in prints[-1]:
        ok("unknown slash is reported")
    else:
        fail(f"unknown command prints {prints}")

    # --- BGSync ---
    bg = addon.GetModule(addon, "BGSync")
    if bg is None:
        fail("BGSync not registered")
    else:
        ok("BGSync registered")
        if bg.enabled:
            ok("BGSync enabled by default")
        else:
            fail("BGSync should default to enabled")

        addon.db.modules.BGSync.stepDelay = 0.1
        addon.db.modules.BGSync.settleDelay = 0.2

        wow.resetChat()
        wow.resetBattleground()
        bg.Start(bg)
        prints = last_prints(lua)
        sent = last_sent(lua)
        if any("not currently in a battleground" in p for p in prints) and sent == []:
            ok("BGSync rejects outside battleground")
        else:
            fail(f"outside BG prints={prints} sent={sent}")

        wow.resetChat()
        set_battleground(
            lua,
            ["Ed", "Bob", "Bob-Realm", "Steve-ChromieCraft", "Ed-Realm"],
            41,
        )
        bg.Start(bg)
        if wow.state.bgScoreRequests == 1:
            ok("BGSync requests battlefield score data")
        else:
            fail(f"bgScoreRequests={wow.state.bgScoreRequests}")
        prints = last_prints(lua)
        if any("Reading battleground roster" in p for p in prints):
            ok("BGSync prints reading roster")
        else:
            fail(f"roster start prints {prints}")

        wow.resetChat()
        bg.Start(bg)
        prints = last_prints(lua)
        if any("already running" in p for p in prints):
            ok("BGSync rejects concurrent start while awaiting scores")
        else:
            fail(f"concurrent awaiting prints {prints}")

        wow.resetChat()
        addon.OnEvent(addon, "UPDATE_BATTLEFIELD_SCORE")
        prints = last_prints(lua)
        if any("Found 2 other players" in p for p in prints):
            ok("BGSync roster excludes self, strips realm, dedupes")
        else:
            fail(f"roster build prints {prints}")

        for _ in range(80):
            if not bg.active and not bg.awaitingScores:
                break
            wow.tick(0.15)
        entries = last_sent_entries(lua)
        msgs = [e["msg"] for e in entries]
        levels = [m for m in msgs if m and m.startswith(".character level ")]
        gears = [e for e in entries if e["msg"] == "autogear"]
        if levels == [
            ".character level Bob 41",
            ".character level Steve 41",
        ]:
            ok("BGSync sends character level commands in roster order")
        else:
            fail(f"level commands {levels}")
        if [e["target"] for e in gears] == ["Bob", "Steve"] and all(
            e["chatType"] == "WHISPER" for e in gears
        ):
            ok("BGSync whispers autogear after settle")
        else:
            fail(f"autogear entries {gears}")
        first_gear = next((i for i, m in enumerate(msgs) if m == "autogear"), -1)
        last_level = max(
            (i for i, m in enumerate(msgs) if m and m.startswith(".character level")),
            default=-1,
        )
        if first_gear > last_level >= 0:
            ok("BGSync runs all level commands before autogear phase")
        else:
            fail(f"phase order msgs={msgs}")
        prints = last_prints(lua)
        if any("Complete. Processed 2 characters at level 41" in p for p in prints):
            ok("BGSync prints completion with captured level")
        else:
            fail(f"completion prints {prints}")
        if not bg.active and not bg.awaitingScores:
            ok("BGSync idle after completion")
        else:
            fail("BGSync still active after completion")

        wow.resetChat()
        set_battleground(lua, ["Ed", "Bob", "Steve"], 41)
        set_friends(lua, ["Bob"])
        bg.Start(bg)
        addon.OnEvent(addon, "UPDATE_BATTLEFIELD_SCORE")
        prints = last_prints(lua)
        if any("Found 1 other players (1 friend skipped)" in p for p in prints):
            ok("BGSync reports friends skipped")
        else:
            fail(f"friends skip prints {prints}")
        for _ in range(80):
            if not bg.active and not bg.awaitingScores:
                break
            wow.tick(0.15)
        entries = last_sent_entries(lua)
        levels = [e["msg"] for e in entries if e["msg"] and e["msg"].startswith(".character level")]
        gears = [e for e in entries if e["msg"] == "autogear"]
        if levels == [".character level Steve 41"] and [e["target"] for e in gears] == ["Steve"]:
            ok("BGSync excludes friends-list names")
        else:
            fail(f"friends exclusion levels={levels} gears={gears}")
        set_friends(lua, [])

        wow.resetChat()
        set_battleground(lua, ["Ed", "Alice"], 41)
        bg.active = True
        bg.awaitingScores = False
        bg.phase = None
        bg.queue = lua.table_from(["Alice"])
        bg.index = 1
        bg.level = 41
        bg.ProcessQueue(bg, bg.runId)
        sent = last_sent(lua)
        if sent == [] and bg.active:
            ok("BGSync nil phase does not send or finish")
        else:
            fail(f"nil phase sent={sent} active={bg.active}")
        bg.index = 2
        wow.resetChat()
        bg.ProcessQueue(bg, bg.runId)
        prints = last_prints(lua)
        sent = last_sent(lua)
        if sent == [] and bg.active and not any("Complete." in p for p in prints):
            ok("BGSync nil phase past end does not Finish")
        else:
            fail(f"nil phase end sent={sent} prints={prints} active={bg.active}")
        bg.Cancel(bg, "test")
        wow.resetChat()

        wow.resetChat()
        set_battleground(lua, ["Ed", "Alice", "Bob"], 41)
        bg.Start(bg)
        addon.OnEvent(addon, "UPDATE_BATTLEFIELD_SCORE")
        wow.tick(0.15)
        wow.resetChat()
        bg.Start(bg)
        prints = last_prints(lua)
        if any("already running" in p for p in prints):
            ok("BGSync rejects concurrent start while processing")
        else:
            fail(f"concurrent processing prints {prints}")
        for _ in range(80):
            if not bg.active and not bg.awaitingScores:
                break
            wow.tick(0.15)

        wow.resetChat()
        set_battleground(lua, ["Ed", "Alice", "Bob", "Carol"], 41)
        bg.Start(bg)
        addon.OnEvent(addon, "UPDATE_BATTLEFIELD_SCORE")
        wow.tick(0.15)
        sent_before = last_sent(lua)
        addon.OnEvent(addon, "PLAYER_LEAVING_WORLD")
        wow.resetChat()
        for _ in range(40):
            wow.tick(0.15)
        sent_after = last_sent(lua)
        if len(sent_before) == 1 and sent_before[0].startswith(".character level"):
            ok("BGSync sent one level command before leave")
        else:
            fail(f"before leave sent {sent_before}")
        if sent_after == [] and not bg.active:
            ok("BGSync cancels queue on PLAYER_LEAVING_WORLD")
        else:
            fail(f"after leave sent={sent_after} active={bg.active}")

        wow.resetChat()
        names = ["Ed"] + [f"Bot{i}" for i in range(1, 40)]
        set_battleground(lua, names, 41)
        addon.db.modules.BGSync.stepDelay = 0.05
        addon.db.modules.BGSync.settleDelay = 0.1
        bg.Start(bg)
        addon.OnEvent(addon, "UPDATE_BATTLEFIELD_SCORE")
        for _ in range(500):
            if not bg.active and not bg.awaitingScores:
                break
            wow.tick(0.06)
        entries = last_sent_entries(lua)
        levels = [e["msg"] for e in entries if e["msg"] and e["msg"].startswith(".character level")]
        gears = [e for e in entries if e["msg"] == "autogear"]
        if len(levels) == 39 and len(gears) == 39:
            ok("BGSync drains full 40-player roster (39 level + 39 autogear)")
        else:
            fail(f"full BG levels={len(levels)} gears={len(gears)} active={bg.active}")
        if all(e["chatType"] == "WHISPER" for e in gears):
            ok("BGSync full-roster autogears are WHISPER")
        else:
            fail("full-roster autogear chat types wrong")

        wow.resetChat()
        wow.resetBattleground()
        addon.SlashHandler(addon, "bgsync status")
        prints = last_prints(lua)
        if prints and "idle" in prints[-1]:
            ok("BGSync status slash works")
        else:
            fail(f"bgsync status prints {prints}")

        addon.db.modules.BGSync.stepDelay = 0.4
        addon.db.modules.BGSync.settleDelay = 1.0

    # Wrong ADDON_LOADED name is ignored after first load (already loaded).
    # Fresh check: config merge keeps user debug=true and fills ui defaults.
    lua.execute("EdsCustomAddonDB = { debug = true, modules = { PartyXP = { enabled = false } } }")
    lua.execute("EdsCustomAddon.loaded = false")
    lua.execute("EdsCustomAddon.ui = nil")
    lua.execute("EdsCustomAddon.modules = {}")
    lua.execute("EdsCustomAddon.moduleOrder = {}")
    addon.LoadConfig(addon)
    db = lua.eval("EdsCustomAddonDB")
    if db.debug:
        ok("config merge keeps existing debug=true")
    else:
        fail("config merge overwrote debug")
    if db.ui is not None and db.ui.point == "CENTER":
        ok("config merge fills missing ui defaults")
    else:
        fail("config merge did not add ui defaults")
    if not db.modules.PartyXP.enabled:
        ok("config merge keeps PartyXP.enabled=false")
    else:
        fail("config merge overwrote PartyXP.enabled")
    if db.modules.BGSync is not None and db.modules.BGSync.enabled:
        ok("config merge fills BGSync defaults")
    else:
        fail("config merge missing BGSync defaults")


def main() -> int:
    if "--manifest-only" in sys.argv:
        print(f"root: {ROOT}")
        sound_pools, sound_durations = generate_sound_manifest()
        sound_count = sum(len(paths) for paths in sound_pools.values())
        if sound_count:
            ok(
                "sound manifest: "
                f"{sound_count} file(s) "
                f"(default={len(sound_pools['default'])}, "
                f"lowhp={len(sound_pools['lowhp'])}, "
                f"kill={len(sound_pools['kill'])}), "
                f"durations={len(sound_durations)}"
            )
        else:
            ok("sound manifest: empty (fallback path or RaidWarning)")
        return 0

    try:
        from lupa import LuaRuntime
    except ImportError:
        print("lupa is required: pip install lupa")
        return 2

    print(f"root: {ROOT}")
    sound_pools, sound_durations = generate_sound_manifest()
    sound_count = sum(len(paths) for paths in sound_pools.values())
    if sound_count:
        ok(
            "sound manifest: "
            f"{sound_count} file(s) "
            f"(default={len(sound_pools['default'])}, "
            f"lowhp={len(sound_pools['lowhp'])}, "
            f"kill={len(sound_pools['kill'])}), "
            f"durations={len(sound_durations)}"
        )
    else:
        ok("sound manifest: empty (fallback path or RaidWarning)")
    lint_toc()
    lint_lua_static()

    lua = LuaRuntime()
    lint_syntax(lua)
    load_addon(lua, ROOT / "scripts" / "wow_env.lua")
    test_addon(lua)

    print()
    if failures:
        print(f"{failures} failure(s)")
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
